### ISSUE TITLE
c.1

### ISSUE THREAD

**Issue by WentingRuan** [WentingRuan/manage-test#4]
# 任务描述
需完成市场信息收集和市场分析

# Task
## 前提任务

- [ ] 市场信息收集
    - [ ] [3](https://github.com/WentingRuan/manage-test/issues/3)
     - [ ] [2](https://github.com/WentingRuan/manage-test/issues/2)
     - [ ] [1](https://github.com/WentingRuan/manage-test/issues/1)

## 当前任务
